name: Test CI/CD

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building"
  development:
    name: Deploy to Development
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - run: echo "Deploying to Development ${{secrets.NAME}}"
  staging:
    name: Deploy to Staging
    needs: [development]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - run: echo "Deploying to Staging ${{secrets.NAME}}"
  production:
    name: Deploy to Production
    needs: [staging]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - run: echo "Deploying to Production ${{secrets.NAME}}"

#  staging:
#  production:
